### ISSUE TITLE
Views are missing

### ISSUE THREAD

**Issue by weedkiller** [Lulubul/Netflix#3]
Hello this is very nice, can you share Views.

Also it would help the community, if we could use this to make our own portal that could hook up a NAS etc.

**Comment by Lulubul** [comment]
Hello! The app is using client-server separation, so you have the REST Web.API and a separate React client APP ( https://github.com/Lulubul/Netflix/tree/master/Netflix/ClientApp ) . The client app is used also for the NeflixContainers ( https://github.com/Lulubul/NeflixContainers ). Hope is helps.
